/**
 * @File Name          : CONSTANTS.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 5/20/2019, 12:37:30 AM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    5/20/2019, 12:33:27 AM   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class CONSTANTS {
	public static final string EMAIL_AVERAGEROW_CONTRACT = 'Weekly Lag,Latest Monthly Average,Normal Monthly Average,';
	public static final string PRICING_EMAIL_TABLE_HEADER_COLOR = '#a67c00';
	public static final string PRICING_EMAIL_TABLE_PASTDATA_COLOR = '#bf9b30';
	public static final string PRICING_EMAIL_TABLE_FUTURE_COLOR = '#ffdc73';
	public static final string PRICING_EMAIL_TABLE_SUMMARY_COLOR = '#ffbf00';
	public static Boolean QUOTE_TRIGGER_EXECUTED = false;
}